account/urls.py
from django.urls import path
from .views import event_approval_list, EventApproveView, SignUpView, ModeratorSignUpView, SecretarySignUpView

app_name = 'account'

urlpatterns = [
    path('event-approval-list/', event_approval_list, name='approval-list'),
    path('event-approval-list/<slug:slug>/approve/', EventApproveView.as_view(), name='approve-event'),
    path('head/register/', SignUpView.as_view(), name='head-register'),
    path('head/register/moderator/', ModeratorSignUpView.as_view(), name='head-register-moderator'),
    path('head/register/secretary/', SecretarySignUpView.as_view(), name='head-register-secretary'),

    path('moderator/register/secretary/', SecretarySignUpView.as_view(), name='moderator-register-secretary'),

]

sweclub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from account.views import StudentSignUpView
from django.contrib import admin
from swehome.views import SearchView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('swehome.urls')),
                  path('blood-donate/', include('blood_donation.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/signup/', StudentSignUpView.as_view(), name='signup'),
                  path('account/', include('account.urls')),
                  path('search/', SearchView.as_view(), name='search'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Software Engineering Club Administration'
admin.site.site_title = 'SWE CLUB'

swehome/urls.py
from django.urls import path
from .views import home_view, EventDetail, EventList, EventPDFView, reply_event, event_create_view, MyEventList,\
    EventDelete, EventUpdateView, ArchivedEventList

app_name = 'swehome'

urlpatterns = [
    path('', home_view, name='home'),
    path('events/create-event/', event_create_view, name='event-create'),
    path('events/', EventList.as_view(), name='event-list'),
    path('events/archived-events/', ArchivedEventList.as_view(), name='archived-event-list'),
    path('events/my-event-list/', MyEventList.as_view(), name='my-event-list'),
    path('events/<slug:slug>/detail/', EventDetail.as_view(), name='event-detail'),
    path('events/<slug:slug>/update/', EventUpdateView.as_view(), name='event-update'),
    path('events/<slug:slug>/delete', EventDelete.as_view(), name='event-delete'),
    path('events/<slug:slug>/detail/reply/', reply_event, name='event-reply'),
    path('events/<slug:slug>/pdf-form/', EventPDFView.as_view(), name='event-form'),
]

swehome/models.py
from account.models import User
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import slugify, Truncator
from markdown import markdown

# Create your models here.


class EventQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (
                        Q(offer_by__icontains=query) |
                        Q(category__icontains=query) |
                        Q(designation__icontains=query) |
                        Q(name__icontains=query) |
                        Q(venue__icontains=query) |
                        Q(chief__icontains=query) |
                        Q(objective__icontains=query) |
                        Q(outcome__icontains=query)
            )
            qs = qs.filter(or_lookup).all()
        return qs


class EventManager(models.Manager):
    def get_queryset(self):
        return EventQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class Event(models.Model):

    category = models.CharField(max_length=10, choices=(
        ('Recent', 'Recent'),
        ('OnGoing', 'OnGoing'),
        ('UpComing', 'UpComing')
    ), null=True, blank=True)
    approved = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    offer_by = models.CharField('Program Offered by', max_length=250, help_text='Department/Section/Club/others name')
    by = models.CharField('Person Responsible', max_length=100)
    height = models.IntegerField(default=0)
    width = models.IntegerField(default=0)
    image = models.ImageField(null=True, blank=True, width_field='width', height_field='height')
    designation = models.CharField(max_length=100)
    mobile = models.CharField(max_length=14)
    name = models.CharField('Program Name', max_length=500)
    venue = models.CharField(max_length=100)
    chief = models.CharField('Chief Guest', max_length=100)
    objective = models.TextField('Objectives of the Program')
    start = models.DateTimeField('Start Time', auto_now_add=False)
    end = models.DateTimeField('End Time', auto_now_add=False)
    target = models.CharField('Target Audience', max_length=100)
    number = models.PositiveIntegerField('Expected Number', default=50)
    outcome = models.TextField('Object Outcome of the Event', null=True, blank=True,
                               help_text='Mention How the Intended Benefit of the Program will be Achieved')
    approval = models.CharField("Program Approval", max_length=100, null=True, blank=True,
                                help_text='Responsible person\'s name with mobile number')
    booking = models.CharField("Venue Booking", max_length=100, null=True, blank=True,
                               help_text='Responsible person\'s name with mobile number')
    reception = models.CharField("Guest Reception", max_length=100, null=True, blank=True,
                                 help_text='Responsible person\'s name with mobile number')

    parking = models.CharField("Car Parking", max_length=100, null=True, blank=True,
                               help_text='Responsible person(s) name with mobile number')
    it = models.CharField('IT Support', max_length=100, null=True, blank=True,
                          help_text='Responsible person\'s name with mobile number')
    banner = models.CharField("Banner Text & Size", max_length=100, null=True, blank=True,
                              help_text='Responsible person\'s name with mobile number')
    security = models.CharField(max_length=100, null=True, blank=True,
                                help_text='Responsible person\'s name with mobile number')
    public_relation = models.CharField("Public Relation", max_length=100, null=True, blank=True,
                                       help_text='Responsible person\'s name with mobile number')
    press = models.CharField("Press Release & Website Text", max_length=100, null=True, blank=True,
                             help_text='Responsible person\'s name with mobile number')
    recording = models.CharField("Video Recording", max_length=100, null=True, blank=True,
                                 help_text='Responsible person\'s name with mobile number')
    tv = models.CharField('Campus TV', max_length=100, null=True, blank=True,
                          help_text='Responsible person\'s name with mobile number')
    decoration = models.CharField("Venue Decoration", max_length=100, null=True, blank=True,
                                  help_text='Responsible person\'s name with mobile number')
    supervision = models.CharField("Cleaning Supervision", max_length=100, null=True, blank=True,
                                   help_text='Responsible person\'s name with mobile number')
    Refreshment = models.CharField(max_length=100, null=True, blank=True,
                                   help_text='Responsible person\'s name with mobile number')
    support = models.CharField("Staff Support", max_length=100, null=True, blank=True,
                               help_text='Responsible person\'s name with mobile number')
    transport = models.CharField("Transport Booking", max_length=100, null=True, blank=True,
                                 help_text='Responsible person\'s name with mobile number')
    extsupport = models.CharField("Extra Support from Outside", max_length=100, null=True, blank=True,
                                  help_text='Responsible person\'s name with mobile number')
    others = models.CharField("Others Requirement", max_length=100, null=True, blank=True,
                              help_text='Responsible person\'s name with mobile number')
    master = models.CharField("Master of Ceremonies", max_length=100, null=True, blank=True,
                              help_text='Responsible person\'s name with mobile number')
    outline = models.CharField("Program Outline & Sequence Confirmed", max_length=100, null=True, blank=True,
                               help_text='Responsible person\'s name with mobile number')
    training = models.CharField("Volunteers & Training", max_length=100, null=True, blank=True,
                                help_text='Responsible person\'s name with mobile number')
    budget = models.CharField("Budget Source", max_length=100, null=True, blank=True,
                              help_text='Responsible person\'s name with mobile number')
    contribution = models.CharField("Departmental Contribution", max_length=100, null=True, blank=True,
                                    help_text='Responsible person\'s name with mobile number')
    sponsor = models.CharField("Sponsor Contribution", max_length=100, null=True, blank=True,
                               help_text='Responsible person\'s name with mobile number')
    slug = models.SlugField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    objects = EventManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('swehome:event-detail', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['-update']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Event, self).save(*args, **kwargs)


class Comment(models.Model):

    message = models.TextField(max_length=4000)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_comments_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

    class Meta:
        ordering = ['-created_at']

swehome/forms.py
from django import forms
from swehome.models import Comment, Event


class EventCreateForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = [
            'offer_by', 'by', 'image', 'designation', 'mobile', 'name', 'venue', 'chief', 'objective', 'start', 'end',
            'target', 'number', 'outcome', 'approval', 'booking', 'reception', 'parking', 'it', 'banner', 'security',
            'public_relation', 'press', 'recording', 'tv', 'decoration', 'supervision', 'Refreshment', 'support',
            'transport', 'extsupport', 'others', 'master', 'outline', 'training', 'budget', 'contribution', 'sponsor'
        ]


class CommentForm(forms.ModelForm):

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 3, 'placeholder': 'What is in your mind?'}
        ), max_length=4000, help_text='The max length of the text is 4000.'
    )

    class Meta:
        model = Comment
        fields = [
            'message',
        ]

swehome/views.py
from itertools import chain

from blood_donation.models import DonationPost
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, ListView, DeleteView, UpdateView
from easy_pdf.views import PDFTemplateResponseMixin
from swehome.forms import CommentForm, EventCreateForm
from .models import Event
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.


def home_view(request):

    recent = Event.objects.filter(category='Recent', approved=True)[:3]
    ongoing = Event.objects.filter(category='OnGoing', approved=True)[:3]
    upcoming = Event.objects.filter(category='UpComing', approved=True)[:3]

    context = {
        'recent': recent,
        'ongoing': ongoing,
        'upcoming': upcoming
    }

    return render(request, 'home.html', context)


@login_required
def event_create_view(request):

    template_name = 'swehome/event-create.html'

    if request.method == 'POST':
        form = EventCreateForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.approved = False
            instance.user = request.user
            instance.save()
            messages.add_message(request, messages.SUCCESS, 'Event Created Successfully! Wait For Approve. Thank You.')
            return redirect('swehome:event-list')
    else:
        form = EventCreateForm()
    return render(request, template_name, {'form': form})


class EventDetail(DetailView):

    queryset = Event.objects.all()


class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventCreateForm
    template_name = 'swehome/event_update.html'
    context_object_name = 'object'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.update = timezone.now()
        post.save()
        messages.add_message(self.request, messages.SUCCESS, 'Event Updated Successfully!')
        return redirect('swehome:event-detail', slug=post.slug)


class EventList(ListView):

    def get_queryset(self):
        queryset = Event.objects.filter(
            Q(approved=True) &
            Q(category__icontains='upcoming') |
            Q(category__icontains='ongoing')
        ).order_by('category')
        return queryset


class MyEventList(LoginRequiredMixin, ListView):

    template_name = 'swehome/my_event_list.html'

    def get_queryset(self):
        queryset = Event.objects.filter(user=self.request.user)
        return queryset


class ArchivedEventList(LoginRequiredMixin, ListView):

    template_name = 'swehome/archived_event_list.html'

    def get_queryset(self):
        queryset = Event.objects.filter(approved=True, category__icontains='recent')
        return queryset


class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('swehome:my-event-list')


class EventPDFView(LoginRequiredMixin, PDFTemplateResponseMixin, DetailView):

    template_name = 'swehome/event-form.html'

    def get_object(self, *args, **kwargs):

        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Event, slug=slug)
        return obj

# class EventForm(DetailView):
#
#     template_name = 'swehome/event-form.html'
#
#     def get_object(self, *args, **kwargs):
#
#         slug = self.kwargs.get('slug')
#         obj = get_object_or_404(Event, slug=slug)
#         return obj


@login_required
def reply_event(request, slug):
    event = get_object_or_404(Event, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.event = event
            post.created_by = request.user
            post.save()

            post.last_updated = timezone.now()
            post.save()
            messages.add_message(request, messages.SUCCESS, 'Thanks for your reply.')
            event_url = reverse('swehome:event-detail', kwargs={'slug': event.slug})
            return redirect(event_url)
    else:
        form = CommentForm()
    return render(request, 'swehome/reply_event.html', {'event': event, 'form': form})


class SearchView(ListView):
    template_name = 'search.html'
    count = 0

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['count'] = self.count or 0
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        request = self.request
        query = request.GET.get('q', None)

        if query is not None:
            event_results = Event.objects.search(query)
            donationpost_results = DonationPost.objects.search(query)

            # combine querysets
            queryset_chain = chain(
                    event_results,
                    donationpost_results
            )
            qs = sorted(queryset_chain,
                        key=lambda instance: instance.pk,
                        reverse=True)
            self.count = len(qs)    # since qs is actually a list
            return qs

swehome/templates/swehome/archived_event_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} Event List | {{ block.super }} {% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item active">Archived Event List</li>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
                <table class="table table-striped">
                    <thead>
                        <tr class="">
                            <th>Event name</th>
                            <th>Offer By</th>
                            <th>Organize By</th>
                            <th>Year</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for obj in object_list %}
                        <tr>
                            <td><a href="{% url 'swehome:event-detail' obj.slug %}">{{ obj.name }}</a></td>
                            <td>{{ obj.offer_by }}</td>
                            <td>{{ obj.by }}</td>
                            <td>{{ obj.update|date:'M/y' }}</td>
                        </tr>
                        {% empty %}
                            <p class="my-3" style="margin-left: 35%">No Event Created Yet.
                                <a class="btn btn-success" href="{% url 'swehome:event-create' %}">Create Event</a>
                            </p>
                    {% endfor %}
                    </tbody>
                </table>


        </div>
    </div>
{% endblock %}

swehome/templates/swehome/event-create.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

    <title>Create Event | SWE CLUB</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.datetimepicker.full.js' %}"></script>

  </head>

  <body>


      <div class="container">
          <ol class="breadcrumb my-1">
              <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
              <li class="breadcrumb-item">Create Event</li>
          </ol>
          <h3 style="text-align: center">Create Event</h3>
          <form enctype="multipart/form-data" class="my-3" method="post" novalidate >{% csrf_token %}
              {% include 'includes/form.html' %}
              <script>
                  $(function () {
                      $('#id_start').datetimepicker({format: 'Y-m-d H:i:s'});
                      $('#id_end').datetimepicker({format: 'Y-m-d H:i:s'});
                  });
              </script>
              <button type="submit" class="btn btn-success btn-block">Create</button>
          </form>
      </div>


  </body>
</html>

swehome/templates/swehome/event_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete | Event</title>
</head>
<body>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
</body>
</html>

swehome/templates/swehome/event_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load humanize %}

{% block title %} {{ object.name }} | {{ block.super }} {% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'swehome:event-list' %}">Events</a></li>
    <li class="breadcrumb-item active">{{ object.name }}</li>
{% endblock %}

{% block content %}
        <div class="row justify-content-center my-3">
            <div class="col-md-8">
                {% if object.image %}
                    <img src="{{ object.image.url }}" alt="{{ object.name }}" height="300" width="700">
                {% endif %}
                <div class="row my-3">
                    <div class="col-6">
                        <h2>{{ object.name }}</h2>
                    </div>
                    {% if object.user == user %}
                        <div class="col-2 text-right">
                            <a class="btn btn-success" href="{% url 'swehome:event-update' slug=object.slug  %}">Update Event</a>
                        </div>
                        <div class="col-2 text-right">
                            <a class="btn btn-success" href="{% url 'swehome:event-delete' slug=object.slug  %}">Delete Event</a>
                        </div>
                        <div class="col-2 text-right">
                            <a class="btn btn-success" href="{% url 'swehome:event-form' slug=object.slug  %}">Get Form</a>
                        </div>
                    {% endif %}
                </div>
                <p>Location: {{ object.venue }}</p>
                <p>Start Time: {{ object.start }}</p>
                <p>End Time: {{ object.end }}</p>
                <p>{{ object.objective }}</p>
            </div>

        </div>
    <div class="container my-3">
        <a href="{% url 'swehome:event-reply' slug=object.slug %}" class="btn btn-success btn-block ">Post a Reply</a>
    </div>

    <div class="container my-3">
        {% for post in object.comments.all %}
        <div class="card {% if forloop.last %} mb-5 {% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
            <div class="card-body p-3">
                <div class="row mb-3">
                    <div class="col-2">
                        <img src="{% static 'img/if_user_309035.svg' %}">
                    </div>
                    <div class="col-10">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">
                                    {{ post.created_by.first_name }} {{ post.created_by.last_name }}
                                </strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at|naturaltime }}</small>
                            </div>
                        </div>
                        {{ post.get_comments_as_markdown }}
                    </div>
                </div>
            </div>
        </div>

        {% empty %}
            <p>No Comments Yet</p>
    {% endfor %}
    </div>

    <hr>


{% endblock %}

swehome/templates/swehome/event_list.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block title %} Event List | {{ block.super }} {% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item active">Event List</li>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <a href="{% url 'swehome:archived-event-list' %}" class="button btn-outline-success">See the Archived Event</a>
        </div>

        <div class="row my-2">
            {% for obj in object_list %}

                {% if forloop.counter|divisibleby:4 %}
                    <div class="col-md-12">
                        <hr class="bg-success">
                    </div>
                {% endif %}

                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'swehome:event-detail' obj.slug %}">{{ obj.name }}</a>
                                <span class="badge badge-pill badge-info">{{ obj.category }}</span>
                            </h5>
                            <p class="card-text">Location: {{ obj.venue }}</p>
                            <p class="card-text">Event Start: {{ obj.start }}</p>
                            <p class="card-text">Event End: {{ obj.end }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Last updated {{ obj.update|naturaltime }}</small>
                        </div>
                    </div>

                </div>

                {% empty %}
                    <p class="my-3" style="margin-left: 40%">No Events Added Yet.
                        <a href="{% url 'swehome:event-create' %}" class="btn btn-info">Create One</a>
                    </p>

            {% endfor %}
        </div>
    </div>
{% endblock %}

swehome/templates/swehome/event_update.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load humanize %}

{% block title %} {{ object.name }} | {{ block.super }} {% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'swehome:my-event-list' %}">Events</a></li>
    <li class="breadcrumb-item"><a href="{% url 'swehome:event-detail' slug=object.slug %}">{{ object.name }}</a></li>
    <li class="breadcrumb-item active">Edit</li>
{% endblock %}

{% block content %}
  <form enctype="multipart/form-data" method="post" class="mb-4" novalidate >

    {% csrf_token %}
    {% include 'includes/form.html' %}
    <div class="row">
        <div class="col-6">
        <button type="submit" class="btn btn-success btn-block">Save changes</button>
    </div>

    <div class="col-6">
        <a href="{% url 'swehome:event-detail' slug=object.slug %}" class="btn btn-outline-secondary btn-block" role="button">
        Cancel
    </a>

    </div>
    </div>


  </form>
{% endblock %}

swehome/templates/swehome/my_event_list.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block title %} Event List | {{ block.super }} {% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item active">My Event List</li>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
                <table class="table table-striped">
                    <thead>
                        <tr class="">
                            <th>Event name</th>
                            <th>Approved</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for obj in object_list %}
                        <tr>
                            <td><a href="{% url 'swehome:event-detail' obj.slug %}">{{ obj.name }}</a></td>
                            {% if obj.approved %}
                                <td>Approved</td>
                            {% else %}
                                <td>Not Approved</td>
                            {% endif %}
                        </tr>
                        {% empty %}
                            <p class="my-3" style="margin-left: 35%">No Event Created Yet.
                                <a class="btn btn-success" href="{% url 'swehome:event-create' %}">Create Event</a>
                            </p>
                    {% endfor %}
                    </tbody>
                </table>


        </div>
    </div>
{% endblock %}

swehome/templates/swehome/reply_event.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Post a reply{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'swehome:event-list' %}">Events</a></li>
    <li class="breadcrumb-item"><a href="{% url 'swehome:event-detail' event.slug %}">{{ event.name }}</a></li>
    <li class="breadcrumb-item active">Post a Reply</li>
{% endblock %}

{% block content %}

    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' with form=form %}
        <button type="submit" class="btn btn-success btn-block">Post a reply</button>
    </form>

{% endblock %}