account/urls.py
from django.urls import path
from .views import event_approval_list, EventApproveView, SignUpView, ModeratorSignUpView, SecretarySignUpView

app_name = 'account'

urlpatterns = [
    path('event-approval-list/', event_approval_list, name='approval-list'),
    path('event-approval-list/<slug:slug>/approve/', EventApproveView.as_view(), name='approve-event'),
    path('head/register/', SignUpView.as_view(), name='head-register'),
    path('head/register/moderator/', ModeratorSignUpView.as_view(), name='head-register-moderator'),
    path('head/register/secretary/', SecretarySignUpView.as_view(), name='head-register-secretary'),

    path('moderator/register/secretary/', SecretarySignUpView.as_view(), name='moderator-register-secretary'),

]

blood_donation/urls.py
from django.urls import path
from .views import blood_donate_view, PostDetailView, reply_donation, add_blood_info, my_blood_info,\
    BloodInfoUpdateView, blood_donation_post, PostDelete, PostUpdateView, my_donation_post_list
app_name = 'blood_donation'

urlpatterns = [

    path('', blood_donate_view, name='blood-home'),
    path('add-blood-info/', add_blood_info, name='add-blood-info'),
    path('my-blood-detail/', my_blood_info, name='blood-info'),
    path('my-blood-detail/<slug:slug>/edit/', BloodInfoUpdateView.as_view(), name='info-update'),
    path('create-donation-post/', blood_donation_post, name='create-post'),
    path('<slug:slug>/detail/', PostDetailView.as_view(), name='post-detail'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<slug:slug>/delete/', PostDelete.as_view(), name='post-delete'),
    path('my-post-list/', my_donation_post_list, name='my-post-list'),
    path('<slug:slug>/detail/reply/', reply_donation, name='post-reply'),
]

sweclub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from account.views import StudentSignUpView
from django.contrib import admin
from swehome.views import SearchView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('swehome.urls')),
                  path('blood-donate/', include('blood_donation.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/signup/', StudentSignUpView.as_view(), name='signup'),
                  path('account/', include('account.urls')),
                  path('search/', SearchView.as_view(), name='search'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Software Engineering Club Administration'
admin.site.site_title = 'SWE CLUB'

swehome/urls.py
from django.urls import path
from .views import home_view, EventDetail, EventList, EventPDFView, reply_event, event_create_view, MyEventList,\
    EventDelete, EventUpdateView, ArchivedEventList

app_name = 'swehome'

urlpatterns = [
    path('', home_view, name='home'),
    path('events/create-event/', event_create_view, name='event-create'),
    path('events/', EventList.as_view(), name='event-list'),
    path('events/archived-events/', ArchivedEventList.as_view(), name='archived-event-list'),
    path('events/my-event-list/', MyEventList.as_view(), name='my-event-list'),
    path('events/<slug:slug>/detail/', EventDetail.as_view(), name='event-detail'),
    path('events/<slug:slug>/update/', EventUpdateView.as_view(), name='event-update'),
    path('events/<slug:slug>/delete', EventDelete.as_view(), name='event-delete'),
    path('events/<slug:slug>/detail/reply/', reply_event, name='event-reply'),
    path('events/<slug:slug>/pdf-form/', EventPDFView.as_view(), name='event-form'),
]

blood_donation/models.py
from account.models import User
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.utils.safestring import mark_safe
from django.utils.text import slugify, Truncator
from markdown import markdown
from .utils import unique_slug_generator


# Create your models here.


class BloodDonor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    group = models.CharField('Blood Group', choices=(('A+', 'A+'),
                                                     ('A-', 'A-'),
                                                     ('B+', 'B+'),
                                                     ('B-', 'B-'),
                                                     ('O+', 'O+'),
                                                     ('O-', 'O-'),
                                                     ('AB+', 'AB+'),
                                                     ('AB-', 'AB-')),
                             max_length=3)
    last_donate = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username + " " + self.group)
        super(BloodDonor, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-update_at']


class DonationPostQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (
                        Q(title__icontains=query) |
                        Q(group__icontains=query) |
                        Q(place__icontains=query) |
                        Q(about__icontains=query)
            )
            qs = qs.filter(or_lookup).all()
        return qs


class DonationPostManager(models.Manager):
    def get_queryset(self):
        return DonationPostQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)


class DonationPost(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    by = models.CharField(max_length=20)
    title = models.CharField(max_length=150)
    group = models.CharField('Blood Group Need', choices=(('A+', 'A+'),
                                                          ('A-', 'A-'),
                                                          ('B+', 'B+'),
                                                          ('B-', 'B-'),
                                                          ('O+', 'O+'),
                                                          ('O-', 'O-'),
                                                          ('AB+', 'AB+'),
                                                          ('AB-', 'AB-')),
                             max_length=3, null=True, blank=True)
    place = models.CharField(max_length=100)
    about = models.TextField('Patient Details', null=True, blank=True)
    contact_number = models.CharField(max_length=50)
    slug = models.SlugField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    objects = DonationPostManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-update_at']


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(rl_pre_save_receiver, sender=DonationPost)


class Comment(models.Model):
    message = models.TextField(max_length=4000)
    donation = models.ForeignKey(DonationPost, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='coments')
    updated_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_comments_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

blood_donation/forms.py
from django import forms
from .models import Comment, BloodDonor, DonationPost


class BloodInfoForm(forms.ModelForm):
    class Meta:
        model = BloodDonor
        fields = [
            'group', 'last_donate'
        ]


class BloodDonationForm(forms.ModelForm):
    class Meta:
        model = DonationPost
        fields = [
            'by', 'title', 'group', 'place', 'about', 'contact_number'
        ]


class CommentForm(forms.ModelForm):

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 3, 'placeholder': 'What is in your mind?'}
        ), max_length=4000, help_text='The max length of the text is 4000.'
    )

    class Meta:
        model = Comment
        fields = [
            'message',
        ]

blood_donation/views.py
from blood_donation.forms import CommentForm, BloodDonationForm, BloodInfoForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, UpdateView, DeleteView, ListView
from .models import BloodDonor, DonationPost
from django.contrib.auth.decorators import login_required
# Create your views here.


def blood_donate_view(request):

    query = DonationPost.objects.all()[:10]

    context = {
        'posts': query,
    }
    return render(request, 'blood_donation/blood-home.html', context)


@login_required
def add_blood_info(request):
    if request.method == 'POST':
        form = BloodInfoForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            a = BloodDonor.objects.filter(user=request.user).exists()
            if a:
                messages.add_message(request, messages.WARNING, 'You Already Added Information')
                return redirect('blood_donation:blood-home')
            post.user = request.user
            post.save()
            messages.add_message(request, messages.SUCCESS, 'Information Added Successfully!')
            return redirect('blood_donation:blood-info')
    else:
        form = BloodInfoForm()
    return render(request, 'blood_donation/blood-info.html', {'form': form})


@login_required
def my_blood_info(request):
    me = BloodDonor.objects.filter(user=request.user)

    context = {
        'object': me
    }
    return render(request, 'blood_donation/blooddonor_detail.html', context)


class BloodInfoUpdateView(LoginRequiredMixin, UpdateView):
    model = BloodDonor
    form_class = BloodInfoForm
    template_name = 'blood_donation/blood-info-update.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.SUCCESS, 'Information Updated Successfully!')
        return redirect('blood_donation:blood-info')


@login_required
def blood_donation_post(request):

    if request.method == 'POST':
        form = BloodDonationForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.save()
            return redirect('blood_donation:blood-home')
    else:
        form = BloodDonationForm()
    return render(request, 'blood_donation/add-post.html', {'form': form})


@login_required
def my_donation_post_list(request):

    q = DonationPost.objects.filter(owner=request.user)

    context = {
        'list': q,
    }
    return render(request, 'blood_donation/donationpost_list.html', context)


class PostDetailView(DetailView):
    queryset = DonationPost.objects.all()


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = DonationPost
    form_class = BloodDonationForm
    template_name = 'blood_donation/post-update.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(owner=self.request.user)

    def form_valid(self, form):
        instance=form.save(commit=False)
        instance.save()
        messages.add_message(self.request, messages.SUCCESS, 'Post Updated Successfully!')
        return redirect('blood_donation:post-detail', slug=instance.slug)


class PostDelete(LoginRequiredMixin, DeleteView):
    model = DonationPost
    success_url = reverse_lazy('blood_donation:blood-home')


@login_required
def reply_donation(request, slug):
    donation = get_object_or_404(DonationPost, slug=slug)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.donation = donation
            post.created_by = request.user
            post.save()

            post.last_updated = timezone.now()
            post.save()
            messages.add_message(request, messages.SUCCESS, 'Thanks for your reply.')
            donation_url = reverse('blood_donation:post-detail', kwargs={'slug': donation.slug})
            return redirect(donation_url)
    else:
        form = CommentForm()
    return render(request, 'blood_donation/reply_donation.html', {'donation': donation, 'form': form})

blood_donation/templates/blood_donation/add-post.html
{% extends 'base.html' %}

{% block title %} Create Post | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item active">Add Blood Donation Post</li>
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-info btn-block">Add</button>
    </form>
{% endblock %}

blood_donation/templates/blood_donation/blood-home.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} Blood Donate | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item active">Blood Donation Post List</li>
{% endblock %}

{% block content %}

    <h3 class="my-3" style="text-align: center">Blood Donation Post</h3>

    <div class="row my-3">
        {% for post in posts %}
            {% if forloop.counter|divisibleby:4 %}
                <div class="col-md-12">
                    <hr class="bg-info">
                </div>
            {% endif %}
            <div class="col-md-4 col-sm-4 col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">
                            <a href="{% url 'blood_donation:post-detail' slug=post.slug %}">{{ post.title }}</a>
                        </h3>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">By {{ post.by }} {{ post.update_at|naturaltime }}</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr class="my-3" style="border: 2px solid #4a95ff">
{% endblock content %}

blood_donation/templates/blood_donation/blood-info-update.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

        <title>Update Blood Info | SWE CLUB</title>

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}">
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/jquery.datetimepicker.full.js' %}"></script>

    </head>

    <body>
        <div class="container">
            <ol class="breadcrumb my-1">
              <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
              <li class="breadcrumb-item"><a href="{% url 'blood_donation:blood-info' %}"> My Blood Info</a></li>
            </ol>
            <form method="post" novalidate>{% csrf_token %}
                {% include 'includes/form.html' with form=form %}
                <script>
                      $(function () {
                          $('#id_last_donate').datetimepicker({format: 'Y-m-d H:i:s'});
                      });
                </script>
                <button type="submit" class="btn btn-info btn-block">Update</button>
            </form>
        </div>
    </body>

blood_donation/templates/blood_donation/blood-info.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-us">
    <head>
        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

        <title>Add Blood Info | SWE CLUB</title>

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery.datetimepicker.min.css' %}">
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/jquery.datetimepicker.full.js' %}"></script>

    </head>

    <body>
        <div class="container">
            <ol class="breadcrumb my-1">
              <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
              <li class="breadcrumb-item active">Add Blood Info</li>
            </ol>
            <form method="post" novalidate>{% csrf_token %}
                {% include 'includes/form.html' with form=form %}
                <script>
                      $(function () {
                          $('#id_last_donate').datetimepicker({format: 'Y-m-d H:i:s'});
                      });
                </script>
                <button type="submit" class="btn btn-info btn-block">Save</button>
            </form>
        </div>
    </body>

blood_donation/templates/blood_donation/blooddonor_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %} My Blood Info | {{ block.super }} {% endblock %}

{% block breadcrumb %}

    <li class="breadcrumb-item">
        <a href="{% url 'swehome:home' %}"> Home</a>
    </li>
    <li class="breadcrumb-item active">
        My Blood Info
    </li>

{% endblock breadcrumb %}

{% block content %}
        <div class="col-md-12 col-sm-12 col-lg-12">
            <div class="card" style="text-align: center">
                <div class="card-body" >
                    {% for i in object %}
                        <p class="card-text">Blood Group {{ i.group }}</p>
                        <P class="card-text">Last Donated {{ i.last_donate|naturaltime }}</P>
                        <a href="{% url 'blood_donation:info-update' slug=i.slug %}" class="btn btn-info">Update</a>
                    {% empty %}
                        <a href="{% url 'blood_donation:add-blood-info' %}" class="btn btn-info">Add Blood Information</a>
                    {% endfor %}
                </div>
            </div>
        </div>


{% endblock %}

blood_donation/templates/blood_donation/donationpost_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete | Event</title>
</head>
<body>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
</body>
</html>

blood_donation/templates/blood_donation/donationpost_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block title %} {{ object.title }} | {{ block.super }} {% endblock %}

{% block breadcrumb %}

    <li class="breadcrumb-item">
        <a href="{% url 'swehome:home' %}"> Home</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'blood_donation:blood-home' %}">Blood Donation Post List</a>
    </li>
    <li class="breadcrumb-item active">{{ object.title }}</li>

{% endblock breadcrumb %}

{% block content %}
        <div class="col-md-12 col-sm-12 col-lg-12">
            <div class="card" style="text-align: center">
                <div class="card-body">
                    <div class="row">
                        {% if object.owner == user %}
                            <div class="col-10">
                                <h3 class="card-title" style="margin-left: 20%">{{ object.title }}</h3>
                            </div>
                            <div class="col-1 text-right">
                                <a class="btn btn-success" href="{% url 'blood_donation:post-update' object.slug  %}">Update</a>
                            </div>
                            <div class="col-1 text-right">
                                <a class="btn btn-success" href="{% url 'blood_donation:post-delete' object.slug  %}">Delete</a>
                            </div>
                        {% else %}
                            <h3 class="card-title" style="margin-left: 40%">{{ object.title }}</h3>
                        {% endif %}
                    </div>
                    <hr>
                    {% if object.group %}
                        <p class="card-text">Blood Group Need: <span>{{ object.group }}</span></p>
                    {% else %}
                        {{ pass }}
                    {% endif %}
                    <P class="card-text">Place: {{ object.place }}</P>
                    {% if object.about %}
                        <p class="card-text">About Patient: {{ object.about }}</p>
                    {% else %}
                        {{ pass }}
                    {% endif %}
                    <p class="card-text">Contact Number: {{ object.contact_number }}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">By {{ object.by }} {{ object.update_at|naturaltime }}</small>
                </div>
            </div>
        </div>

    <div class="container my-3">
        <a href="{% url 'blood_donation:post-reply' slug=object.slug %}" class="btn btn-success btn-block ">
            Post a Reply
        </a>
    </div>

    <div class="container my-3">
        {% for post in object.comments.all %}
        <div class="card mb-2">
            <div class="card-body p-3">
                <div class="row mb-3">
                    <div class="col-2">
                        <img src="{% static 'img/if_user_309035.svg' %}">
                    </div>
                    <div class="col-10">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">
                                    {{ post.created_by.first_name }} {{ post.created_by.last_name }}
                                </strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at|naturaltime }}</small>
                            </div>
                        </div>
                        {{ post.get_comments_as_markdown }}
                    </div>
                </div>
            </div>
        </div>

        {% empty %}
            <p class="text-center">No Comments Yet</p>
    {% endfor %}
    </div>

    <hr>

{% endblock %}

blood_donation/templates/blood_donation/donationpost_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item active">My Blood Donation Post List</li>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>SL</th>
                <th>Name</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for a in list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'blood_donation:post-detail' slug=a.slug %}"> {{ a.title }} </a></td>
                    <td>{{ a.update_at|naturaltime }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

blood_donation/templates/blood_donation/post-update.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Update Post | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item">
        <a href="{% url 'blood_donation:blood-home' %}">Blood Donation Post List</a>
    </li>
    <li class="breadcrumb-item"><a href="{% url 'blood_donation:post-detail' object.slug %}">{{ object.title }}</a></li>
    <li class="breadcrumb-item active">Update</li>
{% endblock %}

{% block content %}

    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' with form=form %}
        <button type="submit" class="btn btn-success btn-block">Post a reply</button>
    </form>

{% endblock %}

blood_donation/templates/blood_donation/reply_donation.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Post a reply{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/simplemde.min.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'js/simplemde.min.js' %}"></script>
  <script>
    var simplemde = new SimpleMDE();
  </script>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}"> Home</a></li>
    <li class="breadcrumb-item">
        <a href="{% url 'blood_donation:blood-home' %}">Blood Donation Post List</a>
    </li>
    <li class="breadcrumb-item"><a href="{% url 'blood_donation:post-detail' donation.slug %}">{{ donation.title }}</a></li>
    <li class="breadcrumb-item active">Post a Reply</li>
{% endblock %}

{% block content %}

    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' with form=form %}
        <button type="submit" class="btn btn-success btn-block">Post a reply</button>
    </form>

{% endblock %}