account/urls.py
from django.urls import path
from .views import event_approval_list, EventApproveView, SignUpView, ModeratorSignUpView, SecretarySignUpView

app_name = 'account'

urlpatterns = [
    path('event-approval-list/', event_approval_list, name='approval-list'),
    path('event-approval-list/<slug:slug>/approve/', EventApproveView.as_view(), name='approve-event'),
    path('head/register/', SignUpView.as_view(), name='head-register'),
    path('head/register/moderator/', ModeratorSignUpView.as_view(), name='head-register-moderator'),
    path('head/register/secretary/', SecretarySignUpView.as_view(), name='head-register-secretary'),

    path('moderator/register/secretary/', SecretarySignUpView.as_view(), name='moderator-register-secretary'),

]

blood_donation/urls.py
from django.urls import path
from .views import blood_donate_view, PostDetailView, reply_donation, add_blood_info, my_blood_info,\
    BloodInfoUpdateView, blood_donation_post, PostDelete, PostUpdateView, my_donation_post_list
app_name = 'blood_donation'

urlpatterns = [

    path('', blood_donate_view, name='blood-home'),
    path('add-blood-info/', add_blood_info, name='add-blood-info'),
    path('my-blood-detail/', my_blood_info, name='blood-info'),
    path('my-blood-detail/<slug:slug>/edit/', BloodInfoUpdateView.as_view(), name='info-update'),
    path('create-donation-post/', blood_donation_post, name='create-post'),
    path('<slug:slug>/detail/', PostDetailView.as_view(), name='post-detail'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<slug:slug>/delete/', PostDelete.as_view(), name='post-delete'),
    path('my-post-list/', my_donation_post_list, name='my-post-list'),
    path('<slug:slug>/detail/reply/', reply_donation, name='post-reply'),
]

sweclub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from account.views import StudentSignUpView
from django.contrib import admin
from swehome.views import SearchView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('swehome.urls')),
                  path('blood-donate/', include('blood_donation.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/signup/', StudentSignUpView.as_view(), name='signup'),
                  path('account/', include('account.urls')),
                  path('search/', SearchView.as_view(), name='search'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Software Engineering Club Administration'
admin.site.site_title = 'SWE CLUB'

swehome/urls.py
from django.urls import path
from .views import home_view, EventDetail, EventList, EventPDFView, reply_event, event_create_view, MyEventList,\
    EventDelete, EventUpdateView, ArchivedEventList

app_name = 'swehome'

urlpatterns = [
    path('', home_view, name='home'),
    path('events/create-event/', event_create_view, name='event-create'),
    path('events/', EventList.as_view(), name='event-list'),
    path('events/archived-events/', ArchivedEventList.as_view(), name='archived-event-list'),
    path('events/my-event-list/', MyEventList.as_view(), name='my-event-list'),
    path('events/<slug:slug>/detail/', EventDetail.as_view(), name='event-detail'),
    path('events/<slug:slug>/update/', EventUpdateView.as_view(), name='event-update'),
    path('events/<slug:slug>/delete', EventDelete.as_view(), name='event-delete'),
    path('events/<slug:slug>/detail/reply/', reply_event, name='event-reply'),
    path('events/<slug:slug>/pdf-form/', EventPDFView.as_view(), name='event-form'),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

    <title>{% block title %}SWE CLUB{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    {% block stylesheet %}{% endblock %}

  </head>

  <body>

    {% block body %}

        <div class="container-fluid bg-info">
            <div class="row">
                <div class="col-md-4" style="text-align: center; margin-top: 14px">
                    info.sweclub@gmail.com
                </div>
                <div class="col-md-4" style="text-align: center; margin-top: 14px">
                    01739209858
                </div>
                <div class="col-md-4" style="text-align: center; margin-top: 6px">
                    {% if user.is_authenticated and user.is_student %}
                        <p class="pt-3">Logged in as <strong>Student</strong>.
                            <a href="{% url 'logout' %}" class="btn btn-outline-dark">Log out</a>
                        </p>
                    {% elif user.is_authenticated and user.is_moderator %}
                        <p class="pt-3">Logged in as <strong>Moderator</strong>.
                            <a href="{% url 'logout' %}" class="btn btn-outline-dark">Log out</a>
                        </p>
                    {% elif user.is_authenticated and user.is_secretary %}
                        <p class="pt-3">Logged in as <strong>Secretary</strong>.
                            <a href="{% url 'logout' %}" class="btn btn-outline-dark">Log out</a>
                        </p>
                    {% elif user.is_authenticated and user.is_head %}
                        <p class="pt-1">Logged in as <strong>Head</strong>.
                            <a href="{% url 'logout' %}" class="btn btn-outline-dark">Log out</a>
                        </p>
                    {% else %}
                        <a href="{% url 'login' %}" class="btn btn-outline-dark" role="button">Log in</a>
                        <a href="{% url 'signup' %}" class="btn btn-outline-dark" role="button">Sign up</a>
                    {% endif %}
                </div>
            </div>

        </div>

        <nav class="navbar navbar-expand-lg navbar-light bg-secondary">

            <a class="navbar-brand" href="{% url 'swehome:home' %}" style="margin-left: 20px">
                <span class="badge badge-pill badge-info">SWE CLUB</span>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse " id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto text-white">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'swehome:home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'swehome:event-list' %}">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blood_donation:blood-home' %}">Blood Donation</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li>
                        <a class="btn badge-pill badge-info my-2 my-sm-0" href="{% url 'search' %}">Search</a>

                    </li>
                </ul>

                {% if user.is_authenticated %}
                    {% if user.is_student %}
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="userMenu" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">{{ user.first_name}} {{ user.last_name }}</a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                    <a class="dropdown-item" href="{% url 'swehome:my-event-list' %}">My Event List</a>
                                    <a class="dropdown-item" href="{% url 'swehome:event-create' %}">Create a Event</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'blood_donation:blood-info' %}">My Blood Information</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:my-post-list' %}">My Post List</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:create-post' %}">Create A Blood Donation Post</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                </div>
                            </li>
                        </ul>
                    {% elif user.is_secretary %}
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">{{ user.first_name}} {{ user.last_name }}</a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                    <a class="dropdown-item" href="{% url 'swehome:my-event-list' %}">My Event List</a>
                                    <a class="dropdown-item" href="{% url 'swehome:event-create' %}">Create a Event</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'blood_donation:blood-info' %}">My Blood Information</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:my-post-list' %}">My Post List</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:create-post' %}">Create A Blood Donation Post</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                </div>
                            </li>
                        </ul>
                    {% elif user.is_moderator %}
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">{{ user.first_name}} {{ user.last_name }}</a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                    <a class="dropdown-item" href="{% url 'account:moderator-register-secretary' %}">Add Secretary</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="/admin/swehome/event/">Modify Event</a>
                                    <a class="dropdown-item" href="/admin/account/student/">Modify Student Info</a>
                                    <a class="dropdown-item" href="{% url 'account:approval-list' %}">Event Approval List</a>
                                    <a class="dropdown-item" href="{% url 'swehome:my-event-list' %}">My Event List</a>
                                    <a class="dropdown-item" href="{% url 'swehome:event-create' %}">Create a Event</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'blood_donation:blood-info' %}">My Blood Information</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:my-post-list' %}">My Post List</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:create-post' %}">Create A Blood Donation Post</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                </div>
                            </li>
                        </ul>
                    {% elif user.is_head %}
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false"><strong>{{ user.first_name}} {{ user.last_name }}</strong></a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                                    <a class="dropdown-item" href="{% url 'account:head-register' %}">Add Moderator / Secretary</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'account:approval-list' %}">Event Approval List</a>
                                    <a class="dropdown-item" href="{% url 'swehome:event-create' %}">Create a Event</a>
                                    <a class="dropdown-item" href="{% url 'swehome:my-event-list' %}">My Event List</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'blood_donation:blood-info' %}">My Blood Information</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:my-post-list' %}">My Post List</a>
                                    <a class="dropdown-item" href="{% url 'blood_donation:create-post' %}">Create A Blood Donation Post</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                                </div>
                            </li>
                        </ul>

                    {% endif %}
                {% endif %}
            </div>
        </nav>

        <div class="container">

            <ol class="breadcrumb my-1">
                {% block breadcrumb %}

                {% endblock %}
            </ol>

            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
            {% endfor %}

            {% block content %}

            {% endblock %}

        </div>

    {% endblock body %}

    <footer class="container bg-info my-3">
        <div class="row">
                <div class="col-4 text-left">
                    <p><strong>Daffodil International University</strong></p>
                </div>
                <div class="col-4 text-center">
                    <p><strong>© 2018 Copyright: Software Engineering Club</strong></p>
                </div>
                <div class="col-4 text-right">
                    <p><strong>Department Of Software Engineering</strong></p>
                </div>
        </div>

    </footer>

    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>

    <script src="{% static 'js/popper.min.js' %}"></script>

    <script src="{% static 'js/bootstrap.js' %}"></script>

    {% block javascript %}{% endblock %}


  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block content %}
    <div id="demo" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/slider.jpg' %}" alt="Los Angeles" height="400px" width="1200px">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/slider.jpg' %}" alt="Chicago" height="400px" width="1200px">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/slider.jpg' %}" alt="New York" height="400px" width="1200px">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>

    </div>

    <hr class="my-3" style="border: 2px solid #17a2b8">

    <h3 class="my-3" style="text-align: center">OnGoing Events</h3>

    <div class="card-deck my-3">
        {% for event in ongoing %}
            <div class="card">
                {% if event.image %}
                    <a href="{{ event.image.url }}"> <img class="card-img-top" src="{{ event.image.url }}" alt="Card image cap" height="350" width="300"></a>
                {% endif %}
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'swehome:event-detail' event.slug %}">{{ event.name }}</a> </h5>
                  <p class="card-text">Event Start: {{ event.start }}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated {{ event.update|naturaltime }}</small>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr class="my-3" style="border: 2px solid #17a2b8">

    <h3 class="my-3" style="text-align: center">UpComing Events</h3>

    <div class="card-deck my-3">
        {% for event in upcoming %}
            <div class="card">
                {% if event.image %}
                    <a href="{{ event.image.url }}"> <img class="card-img-top" src="{{ event.image.url }}" alt="Card image cap" height="350" width="300"></a>
                {% endif %}
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'swehome:event-detail' event.slug %}">{{ event.name }}</a> </h5>
                  <p class="card-text">Event Start: {{ event.start }}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated {{ event.update|naturaltime }}</small>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr class="my-3" style="border: 2px solid #17a2b8">

    <h3 class="my-3" style="text-align: center">Recent Events</h3>

    <div class="card-deck my-3">
        {% for event in recent %}
            <div class="card">
                {% if event.image %}
                    <a href="{{ event.image.url }}"> <img class="card-img-top" src="{{ event.image.url }}" alt="Card image cap" height="350" width="300"></a>
                {% endif %}
                <div class="card-body">
                  <h5 class="card-title"><a href="{% url 'swehome:event-detail' event.slug %}">{{ event.name }}</a> </h5>
                  <p class="card-text">Event Start: {{ event.start }}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated {{ event.update|naturaltime }}</small>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load class_name %}
{% block title %}Search | SWE CLUB{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'swehome:home' %}">Home</a></li>
    <li class="breadcrumb-item">Search Result</li>
{% endblock %}

{% block content %}
    <div class='row title-row my-5'>
        <div class='col-12 py-0'>
            <h3 class='my-0 py-0'>{{ count }} results for <b>{{ query }}</b></h3>
        </div>
    </div>


    {% for object in object_list %}
        {% with object|class_name as klass %}
            {% if klass == 'Event' %}
                <div class='row'>
                    <div class='col-12'>
                        Event post: <a href='{% url 'swehome:event-detail' object.slug %}'>{{ object.name }}</a>
                    </div>
                </div>

            {% elif klass == 'DonationPost' %}
                <div class='row'>
                    <div class='col-12'>
                        Blood Donation Post: <a href='{% url 'blood_donation:post-detail' object.slug %}'>{{ object.title }}</a>
                    </div>
                </div>
            {% else %}
                <div class='row'>
                    <div class='col-12 col-lg-8 offset-lg-4'>
                        <a href=''>{{ object }} | {{ object|class_name }}</a>
                    </div>
                </div>
            {% endif %}

        {% endwith %}

        {% empty %}
            <div class='row'>
                <div class='col-12 col-md-6 mx-auto my-5 py-5'>
                    <form method='GET' class='' action='.'>

                        <div class="input-group form-group-no-border mx-auto" style="margin-bottom: 0; font-size: 32px;">
                            <span class="input-group-addon cfe-nav" style='color:#000'>
                                <i class="fa fa-search" aria-hidden="true"></i>
                            </span>
                            <input type="text" name="q" data-toggle="popover" data-placement="bottom"
                                   data-content="Press enter to search" class="form-control cfe-nav mt-0 py-3"
                                   placeholder="Search..." value="" style="" data-original-title="" title=""
                                   autofocus="autofocus">
                        </div>

                    </form>

                </div>
            </div>

    {% endfor %}
{% endblock %}